"""Generate outputs from quest definitions"""
import json
from pathlib import Path
from .parser import QuestParser
from .validator import QuestValidator
from .npc_generator import QuestNPCGenerator

class QuestGenerator:
    def __init__(self):
        self.parser = QuestParser()
        self.validator = QuestValidator()
        self.npc_generator = QuestNPCGenerator()
        self.output_dir = Path("outputs/quests")
        self.kubejs_dir = self.output_dir / "kubejs/quests"
    
    def generate_all(self):
        """Generate all quest outputs"""
        print("\n📂 Loading quest definitions...")
        quests = self.parser.parse_all()
        
        if not quests:
            print("No quests found in config/quests/")
            return False
        
        print(f"\n🎲 Generating outputs for {len(quests)} quests...")
        
        # Validate first
        if not self.validator.validate_all():
            print("\n⚠️ Validation failed. Fix errors before generating.")
            return False
        
        # Create output directories
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.kubejs_dir.mkdir(parents=True, exist_ok=True)
        
        for quest in quests:
            self.generate_quest(quest)
        
        print(f"\n✅ Generated outputs in {self.output_dir}")
        return True
    
    def generate_quest_by_id(self, quest_id):
        """Generate a single quest by ID"""
        quest = self.parser.parse_quest(quest_id)
        if not quest:
            print(f"Quest '{quest_id}' not found")
            return False
        
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.kubejs_dir.mkdir(parents=True, exist_ok=True)
        
        self.generate_quest(quest)
        print(f"✅ Generated quest: {quest_id}")
        return True
    
    def generate_quest(self, quest):
        """Generate outputs for a single quest"""
        quest_id = quest['id']
        print(f"\n📋 Processing quest: {quest['name']}")
        
        # Generate KubeJS quest definition
        self.generate_kubejs_definition(quest)
        
        # Generate NPC SNBT files
        npcs = self.npc_generator.generate_all_npcs(quest)
        print(f"  ✓ Generated {len(npcs)} NPC files")
        
        # Generate Obsidian markdown
        self.generate_obsidian_note(quest)
    
    def generate_kubejs_definition(self, quest):
        """Generate KubeJS quest definition file"""
        quest_id = quest['id']
        
        js_content = f"""// Generated quest definition for {quest_id}
// DO NOT EDIT MANUALLY - Generated by quest generator

global.quests = global.quests || {{}};

global.quests.{quest_id} = {{
    id: "{quest_id}",
    name: "{quest.get('name', quest_id)}",
    type: "{quest.get('type', 'normal')}",
    description: "{quest.get('description', '')}",
    version: {quest.get('version', 1)},
    stages: {json.dumps(quest.get('stages', {}), indent=4)},
    npcs: {json.dumps(quest.get('npcs', []), indent=4)},
    dialog: {json.dumps(quest.get('dialog', {}), indent=4)}
}};

console.log("[Quests] Loaded {quest_id}");
"""
        
        output_file = self.kubejs_dir / f"{quest_id}.js"
        output_file.write_text(js_content)
        print(f"  ✓ Generated KubeJS: {output_file}")
    
    def generate_obsidian_note(self, quest):
        """Generate Obsidian markdown note"""
        quest_id = quest['id']
        
        frontmatter = f"""---
type: quest
id: {quest_id}
name: {quest.get('name', quest_id)}
type: {quest.get('type', 'normal')}
---
"""
        
        content = f"""# {quest.get('name', quest_id)}

{quest.get('description', '')}

## NPCs Involved
"""
        
        for npc in quest.get('npcs', []):
            content += f"- [[{npc.get('name', npc.get('id'))}]] ({npc.get('role')})\n"
        
        content += "\n## Stages\n"
        
        for stage_num, stage in quest.get('stages', {}).items():
            content += f"""
### Stage {stage_num}: {stage.get('name', 'Untitled')}
{stage.get('description', '')}

**Condition:** {stage.get('condition', stage.get('conditions', 'None'))}
**Dialog:** {stage.get('dialog', 'None')}
"""
        
        if quest.get('reward'):
            content += f"""
## Rewards
{quest.get('reward')}
"""
        
        output_file = self.output_dir / f"{quest_id}.md"
        output_file.write_text(frontmatter + content)
        print(f"  ✓ Generated Obsidian: {output_file}")
